version: '3.8'

services:
  idsgnews:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: idsgnews
    ports:
      - "80:80"
    volumes:
      # 数据持久化
      - ./data:/app/public
      # 日志持久化
      - ./logs:/app/logs
    environment:
      - NODE_ENV=production
      - TZ=Asia/Shanghai
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s